# .streamlit/secrets.toml



OPENAI_API_KEY="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"


MONGO_URI="mongodb+srv://admin_anotai@admin:seKfSpIQlD24Eabr@cluster0.mvixr70.mongodb.net/?retryWrites=true&w=majority"
db_name = "anotai_prod"
